language: node_js

sudo: true
dist: trusty

node_js:
  - '5.6.0'

branches:
  only:
  - master

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
 


cache:
  directories:
    - node_modules

notifications:
  email: false

env:
  global:
    - GIT_NAME=Firdosebanu
    - GIT_EMAIL=Firdosebanu@github.com
    - GIT_DOMAIN=github.com
    - secure: jSXhiLA8DfWrUYu/vVD8QWPMchBno11pPt9r0aX1U9juweUC6Pd0htlzCXw4nuC7DK9UbfT33dJB7bheBW0OJwEyEQqNKDrdPbrpTMmx0gkjgcff5k2SunQi9FKJVWDt6TqFLRklSf1zfC0lAWtmOaPyHHtfplnW2AMksFbfdhw=

before_script:
  - DIST_PATH=$TRAVIS_BUILD_DIR/dist
  - REPO_URL=https://github.com/Firdosebanu/repos.git
  - git config --global user.name "Firdosebanu"
  - git config --global user.email "Firdosebanu@github.com"

after_success:
  - if [[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_PULL_REQUEST == "false" ]]; then
      cd $DIST_PATH;
      git clone https://github.com/Firdosebanu/repos.git dist;
      cd $DIST_PATH && rm -rf *;
      cd $TRAVIS_BUILD_DIR && npm run build;
      cd $DIST_PATH && git add -A && git commit -am "Travis build $TRAVIS_BUILD_NUMBER";
      git push https://github.com/Firdosebanu/repos.git ;
    fi